### PR TITLE
Updated dependencies and fixed compatibility to ghc-7.10.1

### PR DESCRIPTION
**Pull request by achirkin**
Tried to use geojson with latest ghc and ran into several compatibility issues.
Suggest these changes to make it work with GHC 7.10.1

### CODE REVIEW

**Comment by domdere** [comment]
Hmm that travis file looks pretty old, i'll update it to setup a proper environment

**Comment by domdere** [comment]
can you rebase please and see how the 7.10.1 travis build goes pls?

**Comment by achirkin** [comment]
Thanks for such quick response! Rebased.

**Comment by domdere** [comment]
ok, the head build passes even thought the 7.10.1 build fails... I have to look into that `haskell-src-exts` problem and see if its an issue with the PR or the travis environment, oes the build work for you from a clean 7.10 environment?

the 7.8 build is broken though, I have been putting off how I want to handle this, I dont really want macros all over the code.  Since the code itself has been pretty stable, i am thinking of doing one final cut for 7.8 with the latest deps that will build, before doing a major point release where 7.8 support is dropped.

once i've put that out, and I know the 7.10 build issue isnt a problem with this PR, i'm happy to merge this in as it is and tweak the travis file accordingly

**Comment by achirkin** [comment]
But it should not be so bad. On 7.10.1 there is a problem of haskell-src-exts package, I will request change on this too.
In 7.10.1 Foldable toList moved into class itself, and I forgot about that. I call toList now qualified  and I hope it compiles on both platforms.

**Comment by domdere** [comment]
Nice those build errors look pretty trivial

**Comment by achirkin** [comment]
Yep, now only 7.10.1 fails due to haskell-src-exts-1.16.0.1 .

**Comment by achirkin** [comment]
Oh no, my latest commit with parsing changes went here

**Comment by domdere** [comment]
ok cool thanks, ill merge this in later today and make a cut

**Comment by domdere** [comment]
sorry i took so long, ill make a cut soon

**Comment by domdere** [comment]
@achirkin Its been deployed

**Pull request merged**
